---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "asciinema.fullname" . }}-secret
  labels:
    app: {{ template "asciinema.name" . }}
    chart: {{ template "asciinema.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Secret key
  SECRET_KEY_BASE: "{{ .Values.secretKeyBase | b64enc }}"
