---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "asciinema.fullname" . }}-smtp
  labels:
    app: {{ template "asciinema.name" . }}
    chart: {{ template "asciinema.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "asciinema.fullname" . }}-smtp
  template:
    metadata:
      labels:
        app: {{ template "asciinema.fullname" . }}-smtp
    spec:
      containers:
        - name: smtp
          image: {{ template "smtp-image.url" . }}
          envFrom:
            - configMapRef:
                name: {{ template "asciinema.fullname" . }}-config
      restartPolicy: Always
